libraryClass/books/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path

from books import  views
app_name='books'
urlpatterns = [
    # path('',views.home,name="home"),
    path('',views.HomeView.as_view(),name="home"),

    # path('addbook',views.addbook,name="addbook"),
    path('addbook',views.AddBookView.as_view(),name="addbook"),

    # path('viewbook',views.viewbook,name="viewbook"),
    path('viewbook',views.ViewBookView.as_view(),name='viewbook'),

    # path('addbook1',views.addbook1,name="addbook1"),
    path('addbook1',views.AddBook1View.as_view(),name="addbook1"),

    # path('bookdetail/<int:i>',views.bookdetail,name="bookdetail"),
    path('bookdetail/<int:i>',views.BookDetailView.as_view(),name="bookdetail"),

    # path('editbook/<int:i>',views.editbook,name="editbook"),
      path('editbook/<int:i>',views.EditBookView.as_view(),name="editbook"),

    # path('deletebook/<int:i>',views.deletebook,name="deletebook"),
      path('deletebook/<int:i>',views.DeleteBookView.as_view(),name="deletebook"),

    # path('searchbook',views.searchbook,name="searchbook"),
    path('searchbook',views.SearchBookView.as_view(),name="searchbook"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

libraryClass/library/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('user/',include('users.urls')),
]

libraryClass/users/urls.py
from django.contrib import admin
from django.urls import path
from  users import views
app_name='users'
urlpatterns = [
    path('',views.register,name="register"),
    path('login',views.login,name="login"),
    path('logout',views.logout,name="logout"),
]

libraryClass/templates/addbook.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
    {% block title %}
    <title>AddBook</title>
    {% endblock %}
{% block content %}
<h2>Add Book(user defined)</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="mb-3">
        <label class="form-label">Title</label>
        <input type="text" name="t" class="form-control">
    </div>
        <div class="mb-3">
        <label class="form-label">Author</label>
        <input type="text" name="a" class="form-control">
    </div>
        <div class="mb-3">
        <label class="form-label">Price</label>
        <input type="number" name="p" class="form-control">
    </div>
    <div class="mb-3">
        <label class="form-label">Pages</label>
        <input type="number" name="pg" class="form-control">
    </div>
    <div class="mb-3">
        <label class="form-label">Language</label>
        <input type="text" name="l" class="form-control">
    </div>
     <div class="mb-3">
        <label class="form-label">Image</label>
        <input type="file" name="i" class="form-control">
    </div>

        <div class="mb-3">

        <input type="submit" class="btn btn-light">
    </div>
</form>
{% endblock %}

libraryClass/templates/addbook1.html
{%  extends 'base.html'   %}
{% load crispy_forms_tags %}
{% block title %}
    <title> Add1 </title>
     {% endblock %}
{% block content %}
<center><h1>ADD BOOK_1(built-in)</h1></center>
<div class="container w-50 border border-2 px-5 pb-5 pt-5 mt-5">
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit">
  </form>
</div>
{% endblock %}

libraryClass/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Title</title>
    {% endblock %}
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'books:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:addbook' %}">Add book</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'books:addbook1' %}">Add book1</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'books:viewbook' %}">View book</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Login</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
      </ul>
      <form class="d-flex" method="POST"  action="{% url 'books:searchbook' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="text" name="q" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

libraryClass/templates/bookdetail.html
{% extends 'base.html'%}
    {% block title %}
    <title>Book Detail</title>
    {% endblock %}
{% block content %}
<div class="container w-50 mx-auto mt-4">
<h2>Book Detail</h2>
    <table class="table table-bordered mt-4 text-center">
        <tr>
            <th>Title</th>
            <td>{{book.title}}</td>
        </tr>
        <tr>
            <th>Author</th>
            <td>{{book.author}}</td>
        </tr>
            <tr>
            <th>Price</th>
            <td>{{book.price}}</td>
        </tr>
        <tr>
            <th>Pages</th>
            <td>{{book.pages}}</td>
        </tr>
        <tr>
            <th>Language</th>
            <td>{{book.language}}</td>
        </tr>
        <tr>
            <th>Image</th>
            <td><img src=" {{book.image.url}}" height="150px" width="150px"></td>
        </tr>
    </table>
</div>
{% endblock %}

libraryClass/templates/editbook.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
    {% block title %}
    <title>Edit Book</title>
    {% endblock %}
{% block content %}
<h2>Edit Book</h2>
<div class="container w-50 border border-2 px-5 pb-5 pt-5 mt-5">
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit">
  </form>
</div>
{% endblock %}

libraryClass/templates/home.html
{% extends 'base.html'%}
    {% block title %}
    <title>home</title>
    {% endblock %}
{% block content %}
<h2>Welcome to homepage</h2>
{% endblock %}

libraryClass/templates/login.html
{% extends 'base.html'%}
    {% block title %}
    <title>login</title>
    {% endblock %}
{% block content %}
<h2>Welcome to Login page</h2>
{% endblock %}

libraryClass/templates/logout.html
{% extends 'base.html'%}
    {% block title %}
    <title>logout</title>
    {% endblock %}
{% block content %}
<h2>Welcome to Logout page</h2>
{% endblock %}

libraryClass/templates/register.html
{% extends 'base.html'%}
    {% block title %}
    <title>register</title>
    {% endblock %}
{% block content %}
<h2>Register</h2>
{% endblock %}

libraryClass/templates/searchbook.html
{% extends 'base.html'%}
    {% block title %}
    <title>Search book</title>
    {% endblock %}
{% block content %}
<div class="container w-75 mx-auto mt-4 p-5">
<h2>Search Books</h2>
    {% if books%}
      <table class="table table-bordered  text-center">
        <tr>
         <th>Cover</th>
         <th>Title</th>
         <th>Author</th>
         <th>Pages</th>
         <th>Language</th>
         <th>Price</th>
        </tr>
          {% for b in books%}
            <tr>
                <td><img src=" {{b.image.url}}" height="150px" width="150px"></td>
                <td>{{b.title}}</td>
                <td>{{b.author}}</td>
                <td>{{b.pages}}</td>
                <td>{{b.language}}</td>
                <td>{{b.price}}</td>
            </tr>
          {% endfor%}
       </table>
    {% else %}
    <h4>No Results...</h4>
    {% endif %}
</div>
{% endblock %}

libraryClass/templates/viewbook.html
{% extends 'base.html'%}
    {% block title %}
    <title>viewbook</title>
    {% endblock %}
{% block content %}
<h2>View Book</h2>
<!--{{ books }}-->
<div class="container w-75 mt-3 p-5">
<table class="table table-bordered ">
    <tr>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PRICE</th>
        <th>PAGES</th>
        <th>LANGUAGE</th>
        <th>COVER</th>
        <th>ACTIONS</th>
    </tr>
    {% for b in books %}
    <tr>
        <td>{{b.title}}</td>
        <td>{{b.author}}</td>
        <td>{{b.price}}</td>
        <td>{{b.pages}}</td>
        <td>{{b.language}}</td>
        <td><img src="{{b.image.url}}" height="150px" width="150px"></td>
        <td><a class="btn btn-light me-2 mt-2" href="{% url 'books:bookdetail' b.id %}">Detail</a>
            <a class="btn btn-light me-2 mt-2" href="{% url 'books:editbook' b.id %}">Edit</a>
            <a class="btn btn-light me-2 mt-2" href="{% url 'books:deletebook' b.id %}">Delete</a>
        </td>
    </tr>
    {% endfor %}
</table>


<!--    <ol>-->
<!--        {% for b in books %}-->
<!--        <li>Book Details</li>-->
<!--        <ul>-->
<!--            <li>Title-{{b.title}}</li>-->
<!--            <li>Author-{{b.author}}</li>-->
<!--            <li>Price-{{b.price}}</li>-->
<!--            <li>Pages-{{b.pages}}</li>-->
<!--            <li>Language-{{b.language}}</li>-->
<!--            <li>Image-{{b.image}}</li>-->
<!--        </ul>-->
<!--        {% endfor %}-->
<!--    </ol>-->
</div>
{% endblock %}